version: '2.1'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        build: .
        image: airflow_coatue:latest
        restart: always
        depends_on:
            - postgres
            #- datadog
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - DD_SERVICE_NAME=airflow_vdat
            - DD_TRACE_ANALYTICS_ENABLED=true
        labels:
            com.datadoghq.ad.logs: '[{"source": "python", "service": "airflow_vdat"}]'
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
            - ~/.aws/:/usr/local/airflow/.aws/
            - ./jars/:/usr/local/airflow/jars
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
# Uncomment below to test datadog
#    datadog:
#        image: datadog/docker-dd-agent
#        environment:
#             - API_KEY=
#             - DD_LOGS_ENABLED=true
#             - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
#             - DD_PROCESS_AGENT_ENABLED=true
#        volumes:
#             - /var/run/docker.sock:/var/run/docker.sock
#             - /proc/mounts:/host/proc/mounts:ro
#             - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
